require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AppDelivery' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  rn_permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAccuracy', :path => "#{rn_permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{rn_permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{rn_permissions_path}/LocationWhenInUse"
  pod 'Permission-PhotoLibrary', :path => "#{rn_permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{rn_permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Camera', :path => "#{rn_permissions_path}/Camera"
  
  pod 'Firebase/Core', '6.34.0'
  pod 'Firebase/Messaging', '6.34.0'


  target 'AppDeliveryTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  use_flipper!({ 'Flipper' => '0.96.0', 'Flipper-Folly' => '2.6.10', 'Flipper-RSocket' => '~> 1.4' })

  post_install do |installer|
    react_native_post_install(installer)
  end
end